### ISSUE TITLE
Endless loop in latest

### ISSUE THREAD

**Issue by synchrone** [mbucc/shmig#36]
Docker container `mkbucc/shmig:latest` hangs in an endless loop, consuming 100% CPU (one core) after printing `shmig: creating migrations table: shmig_version`.

The only difference is https://github.com/mbucc/shmig/commit/0ef361297118f4c13c416eee244f268c28367259.

The issue is not present in `mkbucc/shmig:verbose`, which is currently built on `2017-07-24T11:48:19.724Z`, and does not have this shebang patch applied.

**Comment by mbucc** [comment]
Wow.

@silenius  I'm going to need to roll your patch back until I figure out what is going on here.

**Comment by synchrone** [comment]
@mbucc can you also trigger a rebuild in https://hub.docker.com/r/mkbucc/shmig/ ?

**Comment by mbucc** [comment]
@synchrone Sure.  Can you give me a test case so I can duplicate this bad behavior?

**Comment by synchrone** [comment]
sure:

*docker-compose.yml*
```
version: '2.1'

services:

  postgres:
    image: kartoza/postgis
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports: ['5452:5432']

  migrations:
    image: mkbucc/shmig:latest
    restart: on-failure
    volumes:
      - ./migrations:/sql
    environment:
      - TYPE=postgresql
      - HOST=postgres
      - PORT=5432
      - DATABASE=gis
      - LOGIN=docker
      - PASSWORD=docker
      - UP_MARK=SHMIG
    command: up
```

*migrations/1509357658-init.sql*
```sql
-- SHMIG

create extension if not exists postgis;

create type kind as enum ('type1');

create table mytable(
    id int primary key
);

```

run `docker-compose up` and after several restarts due to postgres starting up, it should hang for good.
